#!/usr/bin/env python3
"""Build a Tapestry-importable .zip from a JSON spec.

Usage:
    build-tapestry-zip.py spec.json output.zip

The spec is almost exactly the shape of a Tapestry export's root.json (see
tapestry-zip-authoring's SKILL.md for the full field reference), except:

  - `version`, `id`, `createdAt`, `updatedAt` may be omitted; this script fills
    them in (version is always forced to 7, the current schema).
  - Anywhere the real root.json wants a string that is either an external URL
    or a `file:/...`-prefixed reference to a bundled asset, this spec instead
    accepts either a plain string (kept as-is, treated as an external URL) or
    an object `{"bundle": "<path to a local file, relative to the spec file>"}`.
    The script reads that local file, places it in the zip under the correct
    naming convention, and rewrites the field to the matching `file:/...`
    value. This is true for: top-level `thumbnail`, every media item's
    `source`, and every thumbnail rendition's `source` (in
    `item.thumbnail.renditions[].source`).

This script does load-bearing structural validation (required fields per item
type, valid discriminants) but is NOT a substitute for the real app's Zod
validation on import — it exists to make the mechanical parts (zip entry
naming, `file:/` prefixing, version/id defaults) impossible to get wrong by
hand. See tapestry-zip-authoring's SKILL.md for everything this validates and
everything it deliberately leaves for the real importer to catch.
"""

import argparse
import json
import mimetypes
import re
import sys
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path

CURRENT_VERSION = 7

MEDIA_ITEM_TYPES = {"audio", "book", "image", "pdf", "video", "webpage"}
ALL_ITEM_TYPES = MEDIA_ITEM_TYPES | {"text", "actionButton"}
KNOWN_WEBPAGE_TYPES = {"youtube", "vimeo", "iaWayback", "iaAudio", "iaVideo"}
ACTION_TYPES = {"internalLink", "externalLink"}

REQUIRED_ITEM_FIELDS = {
    "text": {"id", "position", "size", "dropShadow", "type", "text"},
    "actionButton": {"id", "position", "size", "dropShadow", "type", "text"},
    "audio": {"id", "position", "size", "dropShadow", "type", "source"},
    "book": {"id", "position", "size", "dropShadow", "type", "source"},
    "image": {"id", "position", "size", "dropShadow", "type", "source"},
    "pdf": {"id", "position", "size", "dropShadow", "type", "source"},
    "video": {"id", "position", "size", "dropShadow", "type", "source"},
    "webpage": {"id", "position", "size", "dropShadow", "type", "source"},
}


class SpecError(Exception):
    pass


def fail(msg):
    raise SpecError(msg)


def file_extension(name):
    """Mirror core/src/utils.ts's fileExtension: split on the LAST dot."""
    if "." not in name:
        return name, None
    stem, ext = name.rsplit(".", 1)
    return stem, ext


def guess_extension(path: Path):
    _, ext = file_extension(path.name)
    if ext:
        return ext
    mime, _ = mimetypes.guess_type(str(path))
    if mime and "/" in mime:
        return mime.split("/")[-1]
    return ""


class ZipBuilder:
    def __init__(self, spec_dir: Path, zf: zipfile.ZipFile):
        self.spec_dir = spec_dir
        self.zf = zf
        self.added_names = set()

    def add_bundle(self, path_prefix: str, ident: str, bundle_rel_path: str):
        """Add a local file to the zip under the naming convention
        '<prefix><ident> (<original-name>).<ext>' and return the file:/ value."""
        src = (self.spec_dir / bundle_rel_path).resolve()
        if not src.is_file():
            fail(f"bundled file not found: {src}")
        stem, ext = file_extension(src.name)
        suffix = f".{ext}" if ext else ""
        entry_name = f"{path_prefix}{ident} ({stem}){suffix}"
        if entry_name in self.added_names:
            fail(f"duplicate zip entry name generated: {entry_name!r} — give items distinct ids")
        self.zf.write(src, entry_name)
        self.added_names.add(entry_name)
        return f"file:/{entry_name}"

    def resolve_field(self, value, path_prefix, ident):
        """A spec field is either a plain string (external URL, left as-is)
        or {"bundle": "<local path>"} (bundled into the zip)."""
        if isinstance(value, str) or value is None:
            return value
        if isinstance(value, dict) and "bundle" in value:
            return self.add_bundle(path_prefix, ident, value["bundle"])
        fail(f"expected a string or {{'bundle': path}}, got: {value!r}")


def rendition_name(item_id, rendition):
    is_auto = rendition.get("isAutoGenerated", True)
    is_primary = rendition.get("isPrimary", True)
    fmt = rendition.get("format", "bin")
    size = rendition.get("size") or {}
    width = size.get("width", 0)
    height = size.get("height", 0)
    auto_prefix = "auto" if is_auto else "custom"
    primary_prefix = "primary" if is_primary else "derived"
    return f"{item_id}-{auto_prefix}-{primary_prefix}-thumbnail-{fmt}-{width}x{height}"


def validate_item(item, index):
    item_type = item.get("type")
    if item_type not in ALL_ITEM_TYPES:
        fail(f"items[{index}]: unknown type {item_type!r} (must be one of {sorted(ALL_ITEM_TYPES)})")
    missing = REQUIRED_ITEM_FIELDS[item_type] - item.keys()
    if missing:
        fail(f"items[{index}] (type={item_type}): missing required field(s) {sorted(missing)}")
    if item_type == "webpage" and item.get("webpageType") not in (None, *KNOWN_WEBPAGE_TYPES):
        fail(f"items[{index}]: webpageType must be one of {sorted(KNOWN_WEBPAGE_TYPES)} or null")
    if item_type == "actionButton" and item.get("actionType") not in (None, *ACTION_TYPES):
        fail(f"items[{index}]: actionType must be one of {sorted(ACTION_TYPES)} or null")
    if item_type == "image" and item.get("actionType") not in (None, *ACTION_TYPES):
        fail(f"items[{index}]: actionType must be one of {sorted(ACTION_TYPES)} or null")


def process_item(builder: ZipBuilder, item, index):
    validate_item(item, index)
    item = dict(item)  # shallow copy; we'll mutate string fields
    item_id = item["id"]

    if item.get("type") in MEDIA_ITEM_TYPES:
        item["source"] = builder.resolve_field(item["source"], "items/", item_id)

    thumbnail = item.get("thumbnail")
    if thumbnail and thumbnail.get("renditions"):
        new_renditions = []
        for rendition in thumbnail["renditions"]:
            rendition = dict(rendition)
            name = rendition_name(item_id, rendition)
            rendition["source"] = builder.resolve_field(rendition["source"], "items/", name)
            new_renditions.append(rendition)
        item["thumbnail"] = {"renditions": new_renditions}

    return item


def build(spec: dict, spec_dir: Path, zf: zipfile.ZipFile):
    builder = ZipBuilder(spec_dir, zf)

    root = dict(spec)
    root["version"] = CURRENT_VERSION
    root.setdefault("id", str(uuid.uuid4()))
    now = datetime.now(timezone.utc).isoformat()
    root.setdefault("createdAt", now)
    root.setdefault("updatedAt", now)
    root.setdefault("description", None)
    root.setdefault("parentId", None)
    root.setdefault("startView", None)
    root.setdefault("groups", [])
    root.setdefault("rels", [])
    root.setdefault("presentation", [])
    root.setdefault("background", "#ffffff")
    root.setdefault("theme", "light")

    if root.get("thumbnail") is not None:
        root["thumbnail"] = builder.resolve_field(root["thumbnail"], "", "thumbnail")

    items = root.get("items") or []
    root["items"] = [process_item(builder, item, i) for i, item in enumerate(items)]

    group_ids = {g["id"] for g in root["groups"]}
    for item in root["items"]:
        if item.get("groupId") and item["groupId"] not in group_ids:
            fail(f"item {item['id']} references unknown groupId {item['groupId']!r}")

    zf.writestr("root.json", json.dumps(root, indent=2))
    return root


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("spec", help="Path to the JSON spec file")
    parser.add_argument("output", help="Path to write the .zip to")
    args = parser.parse_args()

    spec_path = Path(args.spec).resolve()
    spec = json.loads(spec_path.read_text())

    with zipfile.ZipFile(args.output, "w", zipfile.ZIP_DEFLATED) as zf:
        try:
            root = build(spec, spec_path.parent, zf)
        except SpecError as e:
            print(f"error: {e}", file=sys.stderr)
            sys.exit(1)

    print(f"wrote {args.output}")
    print(f"  title: {root.get('title')!r}")
    print(f"  items: {len(root['items'])}")
    print(f"  groups: {len(root['groups'])}  rels: {len(root['rels'])}  presentation steps: {len(root['presentation'])}")


if __name__ == "__main__":
    main()
